#!/bin/bash
#docker run -d --name TorrServer --restart=always -v /torrserver/db:/torrserver/db  -p 8090:8090  torrserver:v102

#targetver=$(awk -v FS="TS_VERSION=" 'NF>1{print $2}' Dockerfile)
REPO="YouROK/TorrServer"
WORKDIR="/root/Docker/TorrServer/"

TARGETVER=$(curl -s "https://api.github.com/repos/$REPO/releases/latest" | awk -F '"' '/tag_name/{print $4}')
cd $WORKDIR
CURRENTVER=$(< current.ver)
echo -e "Latest tag is $TARGETVER\nInstalled tag is $CURRENTVER\n"
echo "$TARGETVER" > target.ver

if [[ "$TARGETVER" != "$CURRENTVER" ]]; then
    echo "Updating ..."
    sed -i "s/^\(ENV TS_VERSION\s*=\s*\).*$/\1$TARGETVER/" Dockerfile
    docker stop TorrServer
    docker rm TorrServer
    echo "$TARGETVER" > current.ver
    cd $WORKDIR
    docker build -t torrserver:$TARGETVER .
    docker run -d --name TorrServer --restart=always -v /torrserver/db:/torrserver/db  -p 8090:8090  torrserver:$TARGETVER
fi

